# Generated by Django 4.1.5 on 2023-02-05 23:06

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('id_proceso', models.CharField(max_length=50, null=True)),
                ('proposito', models.CharField(max_length=300, null=True)),
                ('objetivo', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), null=True, size=None)),
                ('descripcion', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), null=True, size=None)),
                ('responsable', models.CharField(max_length=100, null=True)),
                ('categoria', models.CharField(max_length=50, null=True)),
                ('participantes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), null=True, size=None)),
                ('procesoRelacionado', models.CharField(max_length=100, null=True)),
                ('frecuencia', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proceso_Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='story_media/')),
                ('id_proceso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proceso_documento', related_query_name='proceso_documento', to='proceso.proceso')),
            ],
        ),
    ]
