# Generated by Django 4.1.5 on 2023-01-28 19:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcesoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('id_proceso', models.CharField(max_length=50)),
                ('proposito', models.CharField(max_length=300)),
                ('objetivo', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), size=None)),
                ('descripcion', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), size=None)),
                ('responsable', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=50)),
                ('participantes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('procesoRelacionado', models.CharField(max_length=100)),
                ('frecuencia', models.CharField(max_length=100)),
            ],
        ),
    ]
