# Generated by Django 4.1.5 on 2023-02-05 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proceso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Story_Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='story_media/')),
                ('isTitlePicture', models.BooleanField(null=True)),
                ('story', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='story_media', related_query_name='story_media', to='proceso.story')),
            ],
        ),
        migrations.RemoveField(
            model_name='proceso_documento',
            name='id_proceso',
        ),
        migrations.DeleteModel(
            name='Proceso',
        ),
        migrations.DeleteModel(
            name='Proceso_Documento',
        ),
    ]
