# Generated by Django 4.1.5 on 2023-02-06 00:09

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proceso', '0002_story_story_media_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('id_proceso', models.IntegerField()),
                ('proposito', models.CharField(max_length=300)),
                ('objetivo', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), size=None)),
                ('descripcion', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), size=None)),
                ('responsable', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=50)),
                ('participantes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('proceso_relacionado', models.CharField(max_length=100)),
                ('frecuencia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Proceso_Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('file', models.FileField(null=True, upload_to='proceso_media/')),
                ('proceso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proceso_media', related_query_name='proceso_media', to='proceso.proceso')),
            ],
        ),
    ]
