# Generated by Django 4.1.5 on 2023-02-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proceso', '0005_remove_story_media_story_delete_story_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceso',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
