# Generated by Django 4.1.5 on 2023-02-20 20:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proceso', '0006_proceso_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceso',
            name='categoria',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='descripcion',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='frecuencia',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='id_proceso',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='objetivo',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='participantes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='proceso_relacionado',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='proposito',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='responsable',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
