# Generated by Django 4.1.5 on 2023-02-22 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proceso', '0007_alter_proceso_categoria_alter_proceso_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceso',
            name='metrica',
            field=models.FileField(null=True, upload_to='proceso_media/'),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
