# Generated by Django 4.1.5 on 2023-02-25 22:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proceso', '0008_proceso_metrica_alter_proceso_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceso',
            name='participantes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
    ]
