# Generated by Django 4.1.5 on 2023-03-11 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phases', '0003_alter_phase_id_proyecto'),
        ('proceso', '0009_alter_proceso_participantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceso',
            name='id_fase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='process_list', related_query_name='process_list', to='phases.phase'),
        ),
    ]
