# Generated by Django 4.1.5 on 2023-03-11 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proceso', '0010_proceso_id_fase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proceso',
            name='id_proceso',
        ),
    ]
