# Generated by Django 4.1.5 on 2023-03-29 02:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proceso', '0011_remove_proceso_id_proceso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proceso',
            name='participantes',
        ),
        migrations.AddField(
            model_name='proceso',
            name='participantes',
            field=models.ManyToManyField(blank=True, related_name='participantes_proceso', to=settings.AUTH_USER_MODEL),
        ),
    ]
