# Generated by Django 4.1.7 on 2023-02-25 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyectosmodel',
            name='id_proyect',
        ),
        migrations.RemoveField(
            model_name='proyectosmodel',
            name='manual',
        ),
    ]
