# Generated by Django 4.1.5 on 2023-03-11 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_remove_proyectosmodel_id_proyect_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyectosmodel',
            name='id_users',
        ),
    ]
