# Generated by Django 4.1.5 on 2023-01-29 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0002_remove_documentomodel_url_documentomodel_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentomodel',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='resources'),
        ),
    ]
