# Generated by Django 4.1.5 on 2023-02-14 02:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManualModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('id_manual', models.CharField(max_length=50)),
                ('historia', models.CharField(max_length=300)),
                ('alcance', models.CharField(max_length=300)),
                ('vision', models.CharField(max_length=300)),
                ('mision', models.CharField(max_length=100)),
                ('organizacion_empresa', models.FileField(blank=True, null=True, upload_to='resources')),
                ('organigrama', models.FileField(blank=True, null=True, upload_to='resources')),
                ('vocabulario', models.FileField(blank=True, null=True, upload_to='resources')),
                ('funciones_puestos', models.FileField(blank=True, null=True, upload_to='resources')),
                ('politicas', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), size=None)),
            ],
        ),
    ]
