# Generated by Django 4.1.5 on 2023-02-21 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manualmodel',
            name='id_manual',
        ),
        migrations.RemoveField(
            model_name='manualmodel',
            name='nombre',
        ),
    ]
