# Generated by Django 4.1.5 on 2023-02-25 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_remove_proyectosmodel_id_proyect_and_more'),
        ('manual', '0002_remove_manualmodel_id_manual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualmodel',
            name='id_proyecto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='proyecto', to='proyectos.proyectosmodel'),
            preserve_default=False,
        ),
    ]
