# Generated by Django 4.1.5 on 2023-02-26 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0004_rename_id_proyecto_manualmodel_proyecto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manualmodel',
            old_name='proyecto',
            new_name='id_proyecto',
        ),
    ]
