# Generated by Django 4.1.5 on 2023-03-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
        ('user', '0002_alter_customuser_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='id_role',
        ),
        migrations.AddField(
            model_name='customuser',
            name='id_role',
            field=models.ManyToManyField(to='role.rolemodel'),
        ),
    ]
