# Generated by Django 4.1.5 on 2023-03-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_remove_proyectosmodel_id_proyect_and_more'),
        ('user', '0003_remove_customuser_id_role_customuser_id_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='id_project',
        ),
        migrations.AddField(
            model_name='customuser',
            name='id_project',
            field=models.ManyToManyField(to='proyectos.proyectosmodel'),
        ),
    ]
